apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-main
  labels:
    app: {{ .Release.Name }}-main
data:
  APP_COLOR: {{ .Values.config.main.appColor }}
  WELCOME_MESSAGE: {{ .Values.config.main.welcomeMessage }}
---
{{- if .Values.canary.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-test
  labels:
    app: {{ .Release.Name }}-test
data:
  APP_COLOR: {{ .Values.config.canary.appColor }}
  WELCOME_MESSAGE: {{ .Values.config.canary.welcomeMessage }}
{{- end }}
