{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor-main
  labels:
    app: {{ .Release.Name }}-main
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-main
      release: prometheus
  endpoints:
  - port: http
    path: /metrics

---
{{- if .Values.canary.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor-test
  labels:
    app: {{ .Release.Name }}-test
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-test
      release: prometheus
  endpoints:
  - port: http
    path: /metrics
{{- end }}
{{- end }}
