apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-main
  labels:
    app: {{ .Release.Name }}-main
    release: prometheus
spec:
  selector:
    app: {{ .Release.Name }}-main
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http

---
{{- if .Values.canary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-test
  labels:
    app: {{ .Release.Name }}-test
    release: prometheus
spec:
  selector:
    app: {{ .Release.Name }}-test
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
{{- end }}
